### ISSUE TITLE
For compiling the dll for refrences 

### ISSUE THREAD

**Issue by fuckedd** [ntqueryinformation/Content-Warning-Chair#5]
can you tell us what specific refrences to add so beginners can easily compile withouit getting confused and searching

**Comment by ntqueryinformation** [comment]
[https://i.imgur.com/aBiEz60.png](url)
In the picture above it shows the references, you can also see which ones are missing because it will have a yellow exclamation point next to them.

Get them in this folder of the game
Content Warning\Content Warning_Data\Managed
